kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: parcel-csi-node
  namespace: kube-system
spec:
  template:
    spec:
      containers:
        - name: parcel-plugin
          image: iychoi/parcel-csi-driver:latest
          imagePullPolicy: Always
